[package]
name = "gw2-arcdps-food-reminder"
version = "0.1.0"
edition = "2018"
authors = ["Zerthox <zerthox@gmail.com>"]
repository = "https://github.com/zerthox/gw2-arcdps-food-reminder"

[dependencies]
arcdps = { git = "https://github.com/greaka/arcdps_bindings", branch = "master" }
chrono = { version = "0.4", optional = true }
lazy_static = "1.4"
num_enum = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.21"
strum_macros = "0.21"
windows = "0.18"

[build-dependencies]
proc-macro2 = "1.0"
quote = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
windows = "0.18"

[lib]
name = "arcdps_food_reminder"
crate-type = ["cdylib"]

[features]
default = []
demo = []
log = ["chrono"]
