[package]
name = "gw2-arcdps-food-reminder"
version = "0.2.0"
edition = "2021"
authors = ["Zerthox <zerthox@gmail.com>"]
repository = "https://github.com/zerthox/gw2-arcdps-food-reminder"

[dependencies]
arcdps = { git = "https://github.com/greaka/arcdps_bindings", branch = "master" }
arc_util = { git = "https://github.com/zerthox/gw2-arcdps-utils", branch = "master", features = ["serde"]}
lazy_static = "1.4"
num_enum = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.23"
strum_macros = "0.23"

[build-dependencies]
proc-macro2 = "1.0"
quote = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

[lib]
name = "arcdps_food_reminder"
crate-type = ["cdylib"]

[features]
default = []
demo = []
log = ["arc_util/log"]
