[package]
name = "arcdps_food_reminder"
version = "0.4.0"
edition = "2021"
authors = ["Zerthox <zerthox@gmail.com>"]
repository = "https://github.com/zerthox/arcdps-food-reminder"

[dependencies]
arcdps = "0.7"
arcdps-imgui = { version = "0.8", features = ["tables-api"] }
arc_util = { git = "https://github.com/zerthox/arcdps-utils", branch = "0.5.x", features = ["serde", "settings"] }
once_cell = "1.9"
open = "2.0"
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
windows = { version = "0.33", features = ["System", "Win32_Foundation", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging"] }

[lib]
crate-type = ["cdylib"]

[features]
default = []
demo = []
log = ["arc_util/log"]
