[package]
name = "arcdps_food_reminder"
version = "0.2.3"
edition = "2021"
authors = ["Zerthox <zerthox@gmail.com>"]
repository = "https://github.com/zerthox/gw2-arcdps-food-reminder"

[dependencies]
arcdps = { git = "https://github.com/greaka/arcdps_bindings", branch = "master" }
arc_util = { git = "https://github.com/zerthox/gw2-arcdps-utils", branch = "master", features = ["serde", "settings"]}
lazy_static = "1.4"
num_enum = "0.5"
serde = { version = "1.0", features = ["derive"] }
strum = "0.23"
strum_macros = "0.23"
windows = { version = "0.28", features = ["System", "Win32_Foundation", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging"] }

[build-dependencies]
proc-macro2 = "1.0"
quote = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"

[lib]
crate-type = ["cdylib"]

[features]
default = []
demo = []
log = ["arc_util/log"]
