name: Release CI

on:
  release:
    types: [published, prereleased]

env:
  rustup-settings:
    toolchain: stable
    target: x86_64-pc-windows-msvc
    override: true

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with: ${{ env.rustup-settings }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
